parameters:
    akeneo_measure.convert.measure_converter.class: Akeneo\Bundle\MeasureBundle\Convert\MeasureConverter
    akeneo_measure.manager.measure_manager.class:   Akeneo\Bundle\MeasureBundle\Manager\MeasureManager
    akeneo_measure.measures_config: ~

services:
    Akeneo\Bundle\MeasureBundle\Convert\MeasureConverter:
        arguments: ['%akeneo_measure.measures_config%']

    Akeneo\Bundle\MeasureBundle\Manager\MeasureManager:
        arguments: []
        
    akeneo_measure.measure_converter: '@Akeneo\Bundle\MeasureBundle\Convert\MeasureConverter'
    akeneo_measure.manager: '@Akeneo\Bundle\MeasureBundle\Manager\MeasureManager'
